### ISSUE TITLE
work with express 4?

### ISSUE THREAD

**Issue by angelochen960** [masotime/mock-express#1]
possible?

**Comment by masotime** [comment]
It should work fine, although it's true it is using Express 3.x as a dependency.

Although it is called "mock-express", it is really just designed to facilitate unit-testing of routes.

Thus, if you had some code like

```
app = express()
app.get(...., function(req, res, next) { })
app.post(...., function(req, res next) { })
```

You can now control the `req` and `res` objects that are passed into the route, and inspect to see what changes were made to them (e.g. res.render was called with what model).

Does this answer your question? Maybe if you outline your use case.
