### ISSUE TITLE
Invoke fails with optional param

### ISSUE THREAD

**Issue by Snugug** [masotime/mock-express#11]
I have set up a URL with an optional param:

```
app.get('/teams/new/:step?'
```

When attempting to run `app.invoke('get', '/teams/new');`, I get the following error: `TypeError: Cannot read property \'apply\' of undefined`. However, if I include the optional parameter, `app.invoke` works as expected.

It should be noted I'm using the code from https://github.com/masotime/mock-express/pull/10 as I need `app.get` and `app.set` functionality, and Lodash's `extend` instead of the extend module, but I believe the error is coming from what is currently line 18 in the module

**Comment by masotime** [comment]
Hi @Snugug, could you provide a unit test that causes it to fail?

I've written a unit test that passes just fine, so it seems like something else might be the issue:

```
it('should accept invocations of routes without use of optional parameter', function() {
  var app = MockExpress();
  var invocations = 0;

  app.get('/teams/new/:step?', function(req, res) {
    res.send(req.params.step);
  });

  var req = app.makeRequest();
  var resAssertUndefined = app.makeResponse(function(err, sideEffects) {
    assert.equal(sideEffects.send, undefined);
    invocations += 1;
  });

  var resAssertOne = app.makeResponse(function(err, sideEffects) {
    assert.equal(sideEffects.send, '1');
    invocations += 1;
  });

  app.invoke('get', '/teams/new', req, resAssertUndefined);
  app.invoke('get', '/teams/new/1', req, resAssertOne);
  assert.equal(invocations, 2);
});
```

**Comment by masotime** [comment]
@Snugug Just a quick check - are you still having this issue? Otherwise I'll go ahead and close it.
