### ISSUE TITLE
Instructions on using POST with body

### ISSUE THREAD

**Issue by AmbrosiaDevelopments** [masotime/mock-express#15]
@masotime, I would like to invoke a post call but I cannot figure out how to add a body to my request. I can add `query` parameters okay but there is no example and attempting to add a payload to my `makeRequest` call before the post test doesn't work. Love this little library by the way, thanks.

**Comment by AmbrosiaDevelopments** [comment]
Discovered solution. Client side: `app.makeRequest({'body', JSON.stringify(payload)})`, server side: `app.post('test', function(req, res){ let body = JSON.parse(req.get('body));})`

**Comment by kevinccbsg** [comment]
How this `app.makeRequest({'body', JSON.stringify(payload)})` can work?? It cannot be written with that comma and even if that was `:` it won't work. 
I tried `const req = app.makeRequest({ body: JSON.stringify({}) });` and it does not work. How can I send post values?
