### ISSUE TITLE
'Fork me' link on website points to wrong repo

### ISSUE THREAD

**Issue by jasonkarns** [masotime/mock-express#2]
The Fork Me banner on http://npm.taobao.org/package/mock-express points to https://github.com/cnpm/cnpmjs.org

**Comment by masotime** [comment]
That's interesting. As it stands, I believe http://npm.taobao.org is actually is website that is run based on https://github.com/cnpm/cnpmjs.org, which is why the "fork me" banner links there. It's actually associated with the website rather than my repo itself.
