### ISSUE TITLE
Would recommend mentioning this is designed for Express 3

### ISSUE THREAD

**Issue by sygint** [masotime/mock-express#5]

**Comment by masotime** [comment]
Mentioned in https://github.com/masotime/mock-express/commit/e49cc3d2209adc70e252014df8b631df70dcedc1, thanks for creating this issue 👍

**Comment by sygint** [comment]
Thank you kindly, if you know much about how to update this to Express 4, I'd be willing to help, as it seems to be the cleanest workflow for pure unit testing an express router I've seen

**Comment by masotime** [comment]
I'll see what I can do. The API is now hidden when I took a quick look at Express 4, not sure if it's extractable in a clean fashion.

**Comment by masotime** [comment]
@gnarmedia if you're still interested, I've published v1.0.0 which now uses Express 4.x
